### ISSUE TITLE
assertion failed at: "shared/cfe/edgcpfe/lower_name.c", line 9640

### ISSUE THREAD

**Issue by prehensilecode** [PDB-REDO/libcifpp#10]
libcifpp-2.0.0 from GitHub releases

Environment:
- Red Hat Enterprise Linux 8.1
- Intel compiler icpc 19.1.3.304
- Boost 1.75.0
- cmake 3.19.5

```
[  5%] Built target COMPONENTS
[ 11%] Building CXX object CMakeFiles/cifpp.dir/src/Cif++.cpp.o
/ifs/opt/src/libcifpp-2.0.0/src/Cif++.cpp(3696): internal error: assertion failed at: "shared/cfe/edgcpfe/lower_name.c", line 9640


compilation aborted for /ifs/opt/src/libcifpp-2.0.0/src/Cif++.cpp (code 4)
make[2]: *** [CMakeFiles/cifpp.dir/build.make:108: CMakeFiles/cifpp.dir/src/Cif++.cpp.o] Error 4
make[1]: *** [CMakeFiles/Makefile2:152: CMakeFiles/cifpp.dir/all] Error 2
make: *** [Makefile:160: all] Error 2
```

**Comment by mhekkel** [comment]
Although I'm the last one to claim there are no bugs in my code, this clearly is a problem with the Intel compiler. The assertion failure is a message from within the compiler and it most likely stumbles upon generating template implementations since the line it complains about is the very last line of the source file.

Anyway, this is not something I can fix. You should report this problem to Intel if you want to receive a fix.

regards, -maarten
