### ISSUE TITLE
Warning: port uses /usr/local/var instead of /var

### ISSUE THREAD

**Issue by yurivict** [PDB-REDO/libcifpp#24]
The above warning is printed by the FreeBSD ports framework.
```/var``` should be used instead, regardless of ```PREFIX```.

**Comment by mhekkel** [comment]
Since I now use cmake and GNUInstallDirs exclusively, this means that according to this message there is a bug in cmake. I'm using the variable CMAKE_INSTALL_FULL_LOCALSTATEDIR and that variable should contain the absolute path to the var directory to use.

So I think you should file this as a bug in cmake and/or GNUInstallDirs, if they fix this variable, my code will end up in the right place.

BTW, I thought /usr/local/var was a symlink to something in /var. But maybe that used to be the case long ago. Or I simply do not remember that correctly. It's been a long time since I last used FreeBSD as my main OS.

**Comment by yurivict** [comment]
Ok, thanks.

https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=267748
