### ISSUE TITLE
5.0.9 installs the empty directory /var/cache/libcifpp

### ISSUE THREAD

**Issue by yurivict** [PDB-REDO/libcifpp#43]
... is this intended?

**Comment by mhekkel** [comment]
Yes, it is. Since the update script (cron job) will fill it with up-to-date versions of the dictionary files. The question now of course is, does that update script work at all on FreeBSD?

The install scripts for Debian/Ubuntu make sure they run the update on install, filling that directory with the current version. Well, that is supposed to happen anyway.

**Comment by yurivict** [comment]
These scripts probably don't work on FreeBSD.

**Comment by mhekkel** [comment]
FreeBSD uses periodic, iirc. I'll have a look, if it is doable to port things to FreeBSD.

**Comment by mhekkel** [comment]
> FreeBSD uses periodic, iirc. I'll have a look, if it is doable to port things to FreeBSD.

But that will have to wait a little since I just managed to nuke my VM with FreeBSD doing an update...
