### ISSUE TITLE
components.cif does not download

### ISSUE THREAD

**Issue by sanjusare** [PDB-REDO/libcifpp#47]
The components.cif is not downloaded. My internet connection is functioning well, then is not connection problem.

if I use the command: wget https://ftp.wwpdb.org/pub/pdb/data/monomers/components.cif
I can download it correctly by when I try to do the installation using:
make -S . -B build -DCMAKE_INSTALL_PREFIX=/home/scipion/software/em/xmippSrc-v3.23.07.0/src/libcifpp -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON

I cannot download the file correctly.

**Comment by mhekkel** [comment]
Could you please send the output of the command, so we can try to figure out what is going wrong here?

**Comment by sanjusare** [comment]
Dear Marteen,

I was investigating the problem and seems that the problem is for some
reason the Ubuntu configuration that does not allow me to download from FTP
sites. I tried on other PCs and I was able to download the files normally.
I apologize for the inconvenience, but if you can give me some things to
test in my Ubuntu configuration to allow me to download files from FTP
sites I will be very grateful. I tried disabling the firewal (UFW) but I am
still not able to download from FTP sites from that PC.

Thank you very much in advance,

Santiago

**Comment by mhekkel** [comment]
The URL for components.cif used to be ftp://... meaning it was downloaded using the FTP protocol. But since FTP is being blocked by several sites I changed the url to https://... meaning the file is downloaded using HTTPS. That should always work and even though the URL contains the word ftp, it is not using FTP in any way.

So, you must have hit another problem. And if you have more information about this then please let me know.
